name: wallet_v2
description: Proyecto Wallet para TFG
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.1 # Toast para interacción de usuario
  cupertino_icons: ^1.0.2 # Iconos tipo IOS
  http: ^0.13.5 # Para peticiones html
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/